import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{io}from'socket.io-client';import type{ClientCommand,GameState}from'@kemet/shared';import'./styles.css';
const socket=io(`http://${window.location.hostname}:3001`);
function App(){const[state,setState]=useState<GameState>();const[playerId,setPlayerId]=useState(localStorage.getItem('kemet-player')||'');const[name,setName]=useState('');const[msg,setMsg]=useState('');const[selected,setSelected]=useState<string>();const[units,setUnits]=useState(1);
useEffect(()=>{socket.on('state',setState);return()=>{socket.off('state',setState)}},[]);const me=useMemo(()=>state?.players.find(p=>p.id===playerId),[state,playerId]);
function send(cmd:ClientCommand){socket.emit('command',cmd,(r:any)=>{setMsg(r.ok?'':r.message||'Error');if(r.playerId){setPlayerId(r.playerId);localStorage.setItem('kemet-player',r.playerId)}if(r.state)setState(r.state)});}
if(!state)return <main>Connecting…</main>;if(!me)return <main className="join"><h1>Kemet LAN v0.1</h1><p>Room <b>{state.roomCode}</b></p><input value={name} onChange={e=>setName(e.target.value)} placeholder="Player name"/><button onClick={()=>send({type:'JOIN',name})}>Join game</button><p className="error">{msg}</p></main>;
const active=state.activePlayerId===playerId;const first=state.players[0]?.id===playerId;function territoryClick(id:string){if(!active)return;if(!selected){setSelected(id);return;}if(selected===id){setSelected(undefined);return;}send({type:'MOVE',fromId:selected,toId:id,units});setSelected(undefined)}
return <main><header><div><h1>Kemet LAN v0.1</h1><span>Room {state.roomCode} · Round {state.round}</span></div><div className="toolbar">{!state.started&&first&&<button onClick={()=>send({type:'START'})}>Start game</button>}<button onClick={()=>send({type:'SAVE'})}>Save</button><button onClick={()=>send({type:'LOAD'})}>Load</button></div></header><section className="players">{state.players.map(p=><article className={state.activePlayerId===p.id?'active':''} key={p.id}><b>{p.name}</b><span>{p.color} · ☥ {p.prayer}</span></article>)}</section><div className="layout"><section className="board">{state.territories.map(t=><button key={t.id} onClick={()=>territoryClick(t.id)} className={`territory ${t.kind} ${selected===t.id?'selected':''}`} style={{left:`${t.x}%`,top:`${t.y}%`}}><b>{t.name}</b><small>{Object.entries(t.armies).filter(([,n])=>n>0).map(([id,n])=>`${state.players.find(p=>p.id===id)?.name}: ${n}`).join(' · ')||'Empty'}</small></button>)}</section><aside><h2>{active?'Your turn':'Waiting'}</h2><label>Units<input type="number" min="1" max="10" value={units} onChange={e=>setUnits(Number(e.target.value))}/></label><button disabled={!active||!selected} onClick={()=>selected&&send({type:'RECRUIT',territoryId:selected,units})}>Recruit in selected city</button><button disabled={!active} onClick={()=>send({type:'END_TURN'})}>End turn</button><p className="hint">Move: select an origin, then an adjacent destination. Combat is intentionally blocked in v0.1.</p><p className="error">{msg}</p><h3>History</h3><div className="log">{state.log.map(x=><p key={x.id}>{x.text}</p>)}</div></aside></div></main>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
